//! Integration tests for certificate linting.
//!
//! These tests verify the certificate linting functionality using
//! sample certificates generated by spork-core.

use pki_probe::lint::{CertLinter, LintSeverity};

/// Generate a test certificate using spork-core.
fn generate_test_cert() -> Vec<u8> {
    use spork_core::algo::{AlgorithmId, KeyPair};
    use spork_core::cert::{
        extensions::{BasicConstraints, ExtendedKeyUsage, KeyUsage, KeyUsageFlags, SubjectAltName},
        CertificateBuilder, NameBuilder, Validity,
    };

    let kp = KeyPair::generate(AlgorithmId::EcdsaP256).unwrap();
    let subject = NameBuilder::new("test.example.com")
        .organization("Test Org")
        .country("US")
        .build();

    let cert = CertificateBuilder::new(
        subject,
        kp.public_key_der().unwrap(),
        AlgorithmId::EcdsaP256,
    )
    .validity(Validity::years_from_now(1))
    .basic_constraints(BasicConstraints::end_entity())
    .key_usage(KeyUsage::new(KeyUsageFlags::tls_server()))
    .extended_key_usage(ExtendedKeyUsage::tls_server())
    .subject_alt_name(SubjectAltName::new().dns("test.example.com"))
    .build_and_sign(&kp)
    .unwrap();

    use der::Encode;
    cert.to_der().unwrap()
}

/// Generate a CA certificate for testing.
fn generate_ca_cert() -> Vec<u8> {
    use spork_core::algo::{AlgorithmId, KeyPair};
    use spork_core::cert::{
        extensions::{BasicConstraints, KeyUsage, KeyUsageFlags},
        CertificateBuilder, NameBuilder, Validity,
    };

    let kp = KeyPair::generate(AlgorithmId::EcdsaP256).unwrap();
    let subject = NameBuilder::new("Test CA")
        .organization("Test Org")
        .country("US")
        .build();

    let cert = CertificateBuilder::new(
        subject,
        kp.public_key_der().unwrap(),
        AlgorithmId::EcdsaP256,
    )
    .validity(Validity::years_from_now(20))
    .basic_constraints(BasicConstraints::ca())
    .key_usage(KeyUsage::new(KeyUsageFlags::ca_default()))
    .build_and_sign(&kp)
    .unwrap();

    use der::Encode;
    cert.to_der().unwrap()
}

/// Generate a certificate with RSA-2048 key.
fn generate_rsa_cert() -> Vec<u8> {
    use spork_core::algo::{AlgorithmId, KeyPair};
    use spork_core::cert::{
        extensions::{BasicConstraints, ExtendedKeyUsage, KeyUsage, KeyUsageFlags, SubjectAltName},
        CertificateBuilder, NameBuilder, Validity,
    };

    let kp = KeyPair::generate(AlgorithmId::Rsa2048).unwrap();
    let subject = NameBuilder::new("rsa.example.com")
        .organization("Test Org")
        .build();

    let cert = CertificateBuilder::new(subject, kp.public_key_der().unwrap(), AlgorithmId::Rsa2048)
        .validity(Validity::years_from_now(1))
        .basic_constraints(BasicConstraints::end_entity())
        .key_usage(KeyUsage::new(KeyUsageFlags::tls_server()))
        .extended_key_usage(ExtendedKeyUsage::tls_server())
        .subject_alt_name(SubjectAltName::new().dns("rsa.example.com"))
        .build_and_sign(&kp)
        .unwrap();

    use der::Encode;
    cert.to_der().unwrap()
}

// ============================================================================
// CertLinter Tests
// ============================================================================

#[test]
fn test_linter_creation() {
    let linter = CertLinter::new();
    // Linter should be created successfully
    assert!(std::mem::size_of_val(&linter) > 0);
}

#[test]
fn test_linter_with_skip_info() {
    let linter = CertLinter::new().skip_info();
    let cert = generate_test_cert();

    let results = linter.lint_chain(&[cert]);
    // No info-level results should be present
    for result in &results {
        assert_ne!(
            result.severity,
            LintSeverity::Info,
            "Info severity should be skipped"
        );
    }
}

#[test]
fn test_lint_single_certificate() {
    let linter = CertLinter::new();
    let cert = generate_test_cert();

    let results = linter.lint_chain(&[cert]);
    // Should return some results
    // The exact results depend on the certificate properties
    assert!(results
        .iter()
        .all(|r| r.cert_index.is_some() || r.cert_index.is_none()));
}

#[test]
fn test_lint_ca_certificate() {
    let linter = CertLinter::new();
    let cert = generate_ca_cert();

    let results = linter.lint_chain(&[cert]);
    // CA certificate should have specific lint results
    // At minimum, it should be successfully linted
    for result in &results {
        assert!(!result.rule_id.is_empty());
        assert!(!result.message.is_empty());
    }
}

#[test]
fn test_lint_certificate_chain() {
    let linter = CertLinter::new();
    let ca_cert = generate_ca_cert();
    let ee_cert = generate_test_cert();

    let results = linter.lint_chain(&[ee_cert, ca_cert]);
    // Should check both certificates and chain structure
    // Results should reference the correct certificate index
    for result in &results {
        if let Some(idx) = result.cert_index {
            assert!(idx < 2, "Certificate index should be valid");
        }
    }
}

/// RSA-2048 lint check
#[test]
fn test_lint_rsa_certificate() {
    let linter = CertLinter::new();
    let cert = generate_rsa_cert();

    let results = linter.lint_chain(&[cert]);
    // RSA certificate should be linted successfully
    // May have different results than ECDSA certificates
    for result in &results {
        assert!(!result.rule_id.is_empty());
    }
}

#[test]
fn test_lint_empty_chain() {
    let linter = CertLinter::new();
    let results = linter.lint_chain(&[]);

    // Empty chain should return no results or just chain-level issues
    // This verifies the linter handles edge cases gracefully
    for result in &results {
        // If there are results, they should be chain-level (no cert index)
        // or have a valid format
        assert!(!result.rule_id.is_empty());
    }
}

#[test]
fn test_lint_skip_rules() {
    let linter = CertLinter::new().skip_rules(vec!["WEAK_KEY".to_string()]);
    let cert = generate_test_cert();

    let results = linter.lint_chain(&[cert]);
    // The WEAK_KEY rule should not appear
    for result in &results {
        assert_ne!(result.rule_id, "WEAK_KEY");
    }
}

// ============================================================================
// LintSeverity Tests
// ============================================================================

#[test]
fn test_lint_severity_display() {
    assert_eq!(LintSeverity::Info.to_string(), "INFO");
    assert_eq!(LintSeverity::Warning.to_string(), "WARN");
    assert_eq!(LintSeverity::Error.to_string(), "ERROR");
    assert_eq!(LintSeverity::Critical.to_string(), "CRITICAL");
}

#[test]
fn test_lint_severity_ordering() {
    // Severity levels should be comparable
    assert_eq!(LintSeverity::Info, LintSeverity::Info);
    assert_ne!(LintSeverity::Info, LintSeverity::Warning);
    assert_ne!(LintSeverity::Warning, LintSeverity::Error);
    assert_ne!(LintSeverity::Error, LintSeverity::Critical);
}

// ============================================================================
// Bug #34: Lint incorrectly flags CA certificates
// ============================================================================

/// Regression test for issue #34: the linter applied leaf-cert rules
/// (VALIDITY_TOO_LONG, MISSING_SAN) to CA certificates at index 0 when
/// the CA was the only cert in the chain.
///
/// CA certs are permitted long validity periods and are not required to carry
/// a Subject Alternative Name.
#[test]
fn issue_34_lint_does_not_flag_ca_cert_validity_too_long() {
    let linter = CertLinter::new();
    let ca_cert = generate_ca_cert();

    let results = linter.lint_chain(&[ca_cert]);

    let offending: Vec<_> = results
        .iter()
        .filter(|r| r.rule_id == "VALIDITY_TOO_LONG")
        .collect();

    assert!(
        offending.is_empty(),
        "CA certificate should not trigger VALIDITY_TOO_LONG, but got: {:?}",
        offending
    );
}

#[test]
fn issue_34_lint_does_not_flag_ca_cert_missing_san() {
    let linter = CertLinter::new();
    let ca_cert = generate_ca_cert();

    let results = linter.lint_chain(&[ca_cert]);

    let offending: Vec<_> = results
        .iter()
        .filter(|r| r.rule_id == "MISSING_SAN")
        .collect();

    assert!(
        offending.is_empty(),
        "CA certificate should not trigger MISSING_SAN, but got: {:?}",
        offending
    );
}
